title: <p align="center"> Arindam Mondal </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/Profile.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/arindam-mondal-89994b6/">LinkedIn</a> |
  
  </p>



theme: jekyll-theme-minimal
